const fileHandlingTest = [
  {
    id: 1,
    question: "Which function is used to open a file in Python?",
    options: ["open()", "file()", "read()", "os.open()"],
    correctAnswer: "open()",
  },
  {
    id: 2,
    question: "Which mode is used to open a file for writing only?",
    options: ["'r'", "'a'", "'w'", "'rw'"],
    correctAnswer: "'w'",
  },
  {
    id: 3,
    question: "What does the 'r' mode do?",
    options: ["Reads file", "Writes file", "Appends file", "Deletes file"],
    correctAnswer: "Reads file",
  },
  {
    id: 4,
    question: "What happens if a file does not exist in 'r' mode?",
    options: ["It is created", "Error is raised", "It appends", "Nothing happens"],
    correctAnswer: "Error is raised",
  },
  {
    id: 5,
    question: "Which method is used to read entire file content?",
    options: ["readline()", "read()", "readlines()", "fetch()"],
    correctAnswer: "read()",
  },
  {
    id: 6,
    question: "Which method reads a single line from a file?",
    options: ["read()", "readline()", "readlines()", "input()"],
    correctAnswer: "readline()",
  },
  {
    id: 7,
    question: "What does the 'w' mode do if file already exists?",
    options: ["Appends content", "Throws error", "Deletes file", "Overwrites file"],
    correctAnswer: "Overwrites file",
  },
  {
    id: 8,
    question: "Which mode is used to append data to a file?",
    options: ["'r'", "'w'", "'a'", "'rw'"],
    correctAnswer: "'a'",
  },
  {
    id: 9,
    question: "How to close a file in Python?",
    options: ["file.end()", "file.finish()", "file.close()", "file.exit()"],
    correctAnswer: "file.close()",
  },
  {
    id: 10,
    question: "Which method reads all lines into a list?",
    options: ["readline()", "readlines()", "lines()", "read()"],
    correctAnswer: "readlines()",
  },
  {
    id: 11,
    question: "What is the benefit of using 'with open()'?",
    options: ["Automatically closes file", "Reads faster", "Increases memory", "Nothing"],
    correctAnswer: "Automatically closes file",
  },
  {
    id: 12,
    question: "Which method is used to write text to a file?",
    options: ["write()", "read()", "append()", "add()"],
    correctAnswer: "write()",
  },
  {
    id: 13,
    question: "What type does read() return?",
    options: ["list", "int", "str", "file"],
    correctAnswer: "str",
  },
  {
    id: 14,
    question: "Which file mode allows both reading and writing?",
    options: ["'w'", "'r'", "'rw'", "'r+'"],
    correctAnswer: "'r+'",
  },
  {
    id: 15,
    question: "What is the default file mode in open()?",
    options: ["'r'", "'w'", "'a'", "'r+'"],
    correctAnswer: "'r'",
  },
  {
    id: 16,
    question: "Which keyword is used for file context management?",
    options: ["use", "with", "file", "as"],
    correctAnswer: "with",
  },
  {
    id: 17,
    question: "Which statement is correct about file.close()?",
    options: ["It reads the file", "It deletes the file", "It closes the file", "It creates the file"],
    correctAnswer: "It closes the file",
  },
  {
    id: 18,
    question: "What happens if you write to a file opened in 'r' mode?",
    options: ["Writes successfully", "Overwrites file", "Error occurs", "Appends to file"],
    correctAnswer: "Error occurs",
  },
  {
    id: 19,
    question: "How can you read file line-by-line in loop?",
    options: ["for line in file:", "file = open(); file.read()", "file.readlines()", "None"],
    correctAnswer: "for line in file:",
  },
  {
    id: 20,
    question: "What is returned by write() method?",
    options: ["Nothing", "Number of characters written", "True/False", "Bytes"],
    correctAnswer: "Number of characters written",
  },
  {
    id: 21,
    question: "Which module helps in file handling apart from open()?",
    options: ["os", "math", "sys", "re"],
    correctAnswer: "os",
  },
  {
    id: 22,
    question: "Which method checks file existence in os module?",
    options: ["os.file_exists()", "os.path.exists()", "file.check()", "os.exist()"],
    correctAnswer: "os.path.exists()",
  },
  {
    id: 23,
    question: "Which method removes a file?",
    options: ["os.remove()", "file.delete()", "file.remove()", "os.del()"],
    correctAnswer: "os.remove()",
  },
  {
    id: 24,
    question: "How to open a file in binary mode?",
    options: ["'b'", "'binary'", "'rb'", "'br'"],
    correctAnswer: "'rb'",
  },
  {
    id: 25,
    question: "What is the use of seek() method?",
    options: ["Change file name", "Move cursor", "Edit file", "Close file"],
    correctAnswer: "Move cursor",
  },
  {
    id: 26,
    question: "What is the output of file.tell()?",
    options: ["Current line number", "Total lines", "Current cursor position", "Nothing"],
    correctAnswer: "Current cursor position",
  },
  {
    id: 27,
    question: "How to read only 5 characters from file?",
    options: ["file.read(5)", "file.readfive()", "file.readchars(5)", "file.input(5)"],
    correctAnswer: "file.read(5)",
  },
  {
    id: 28,
    question: "Which of the following is not a valid file mode?",
    options: ["'x'", "'z'", "'a'", "'rb'"],
    correctAnswer: "'z'",
  },
  {
    id: 29,
    question: "Which method writes multiple lines to a file?",
    options: ["write()", "writelines()", "addlines()", "insertlines()"],
    correctAnswer: "writelines()",
  },
  {
    id: 30,
    question: "Which of the following opens file for exclusive creation?",
    options: ["'x'", "'w'", "'a'", "'rw'"],
    correctAnswer: "'x'",
  },
];

export default fileHandlingTest;
