const listsTest = [
  {
    id: 1,
    question: "Which of the following defines a list in Python?",
    options: ["list = {}", "list = []", "list = ()", "list = <>"],
    correctAnswer: "list = []",
  },
  {
    id: 2,
    question: "What will be the output?\nlist = [1, 2, 3]\nprint(list[1])",
    options: ["1", "2", "3", "Error"],
    correctAnswer: "2",
  },
  {
    id: 3,
    question: "Which method is used to add an item to the end of the list?",
    options: ["add()", "insert()", "append()", "extend()"],
    correctAnswer: "append()",
  },
  {
    id: 4,
    question: "Which method adds multiple elements to a list?",
    options: ["add()", "append()", "extend()", "insert()"],
    correctAnswer: "extend()",
  },
  {
    id: 5,
    question: "Which of the following removes a specified item from the list?",
    options: ["delete()", "pop()", "remove()", "discard()"],
    correctAnswer: "remove()",
  },
  {
    id: 6,
    question: "What will `list.pop()` do?",
    options: ["Remove first item", "Remove last item", "Delete list", "Do nothing"],
    correctAnswer: "Remove last item",
  },
  {
    id: 7,
    question: "How can you change the value at index 2 of a list?",
    options: ["list[2] = value", "list[2] == value", "change(list, 2, value)", "update(2, value)"],
    correctAnswer: "list[2] = value",
  },
  {
    id: 8,
    question: "Which list method reverses the list?",
    options: ["flip()", "reverse()", "revert()", "turn()"],
    correctAnswer: "reverse()",
  },
  {
    id: 9,
    question: "What is the output?\nlist = [5, 3, 1, 4]; list.sort()\nprint(list)",
    options: ["[5, 3, 1, 4]", "[1, 3, 4, 5]", "[4, 1, 3, 5]", "Error"],
    correctAnswer: "[1, 3, 4, 5]",
  },
  {
    id: 10,
    question: "Which operator is used to repeat a list?",
    options: ["*", "+", "-", "//"],
    correctAnswer: "*",
  },
  {
    id: 11,
    question: "Which keyword is used to check if an item exists in a list?",
    options: ["in", "if", "exists", "has"],
    correctAnswer: "in",
  },
  {
    id: 12,
    question: "What is the result of len([10, 20, 30])?",
    options: ["2", "3", "4", "30"],
    correctAnswer: "3",
  },
  {
    id: 13,
    question: "What is list slicing?\nlist[1:4]",
    options: ["Items from 1 to 4", "Items from 1 to 3", "Items from 0 to 4", "Items from 2 to 4"],
    correctAnswer: "Items from 1 to 3",
  },
  {
    id: 14,
    question: "How do you insert an element at index 2?",
    options: ["list.add(2, x)", "list[2] = x", "list.insert(2, x)", "list.put(2, x)"],
    correctAnswer: "list.insert(2, x)",
  },
  {
    id: 15,
    question: "What is the output?\nlist = [1, [2, 3], 4]\nprint(list[1][1])",
    options: ["1", "2", "3", "[2, 3]"],
    correctAnswer: "3",
  },
  {
    id: 16,
    question: "Which method clears the entire list?",
    options: ["clear()", "removeAll()", "delete()", "empty()"],
    correctAnswer: "clear()",
  },
  {
    id: 17,
    question: "What does `list.index(4)` return?",
    options: ["Value of item 4", "Index of first occurrence of 4", "Length", "Error"],
    correctAnswer: "Index of first occurrence of 4",
  },
  {
    id: 18,
    question: "Which loop is best to iterate a list?",
    options: ["for loop", "while loop", "do-while loop", "if statement"],
    correctAnswer: "for loop",
  },
  {
    id: 19,
    question: "How do you copy a list?",
    options: ["list2 = list", "list2 = list.copy()", "copy(list)", "list.clone()"],
    correctAnswer: "list2 = list.copy()",
  },
  {
    id: 20,
    question: "What is a list comprehension?",
    options: ["Simple loop", "Function", "Short way to create list", "Class"],
    correctAnswer: "Short way to create list",
  },
  {
    id: 21,
    question: "Which method counts occurrences of an item?",
    options: ["total()", "count()", "repeat()", "number()"],
    correctAnswer: "count()",
  },
  {
    id: 22,
    question: "What is the output?\nlist = ['a', 'b'] + ['c']",
    options: ["['a', 'b', 'c']", "['abc']", "['a', 'b', 'c']'", "Error"],
    correctAnswer: "['a', 'b', 'c']",
  },
  {
    id: 23,
    question: "What is the index of first element in list?",
    options: ["0", "1", "-1", "None"],
    correctAnswer: "0",
  },
  {
    id: 24,
    question: "How do you get last item of list?",
    options: ["list[last]", "list[-1]", "list[1]", "list(end)"],
    correctAnswer: "list[-1]",
  },
  {
    id: 25,
    question: "Which operator concatenates two lists?",
    options: ["+", "*", "&", "//"],
    correctAnswer: "+",
  },
  {
    id: 26,
    question: "Can list contain elements of different types?",
    options: ["Yes", "No", "Only strings", "Only numbers"],
    correctAnswer: "Yes",
  },
  {
    id: 27,
    question: "What is output?\nlist = [1, 2, 3]\ndel list[1]\nprint(list)",
    options: ["[1, 3]", "[2, 3]", "[1, 2]", "Error"],
    correctAnswer: "[1, 3]",
  },
  {
    id: 28,
    question: "Which of the following is immutable?",
    options: ["List", "Set", "Tuple", "Dictionary"],
    correctAnswer: "Tuple",
  },
  {
    id: 29,
    question: "How to sort a list in descending order?",
    options: ["list.sort(desc=True)", "list.sort(reverse=True)", "list.desc()", "sort(list)"],
    correctAnswer: "list.sort(reverse=True)",
  },
  {
    id: 30,
    question: "What is the output?\nlist = [1, 2, 3] * 2",
    options: ["[1, 2, 3, 1, 2, 3]", "[2, 4, 6]", "[1, 2, 3, 2]", "[1, 2, 3]"],
    correctAnswer: "[1, 2, 3, 1, 2, 3]",
  },
];

export default listsTest;
