const loopsTest = [
  {
    id: 1,
    question: "Which loop is used to iterate a block of code a known number of times?",
    options: ["while loop", "for loop", "do-while loop", "foreach loop"],
    correctAnswer: "for loop",
  },
  {
    id: 2,
    question: "Which loop continues until a condition becomes false?",
    options: ["for", "while", "do-while", "repeat"],
    correctAnswer: "while",
  },
  {
    id: 3,
    question: "What is the output?\nfor i in range(3): print(i)",
    options: ["1 2 3", "0 1 2", "0 1 2 3", "1 2"],
    correctAnswer: "0 1 2",
  },
  {
    id: 4,
    question: "Which function returns a sequence of numbers?",
    options: ["sequence()", "range()", "loop()", "series()"],
    correctAnswer: "range()",
  },
  {
    id: 5,
    question: "How many times will this run?\nfor i in range(5):",
    options: ["4", "5", "6", "Infinite"],
    correctAnswer: "5",
  },
  {
    id: 6,
    question: "What will break do in a loop?",
    options: ["Exit loop", "Pause loop", "Skip iteration", "Restart loop"],
    correctAnswer: "Exit loop",
  },
  {
    id: 7,
    question: "What is the output?\ni = 1\nwhile i < 4:\n print(i)\n i += 1",
    options: ["1 2 3", "0 1 2", "1 2 3 4", "2 3 4"],
    correctAnswer: "1 2 3",
  },
  {
    id: 8,
    question: "Which loop runs at least once?",
    options: ["for", "while", "do-while (in other languages)", "None"],
    correctAnswer: "do-while (in other languages)",
  },
  {
    id: 9,
    question: "What is the use of `continue` in a loop?",
    options: ["Exit loop", "Skip current iteration", "End program", "Repeat loop"],
    correctAnswer: "Skip current iteration",
  },
  {
    id: 10,
    question: "Which keyword is used to start a loop in Python?",
    options: ["loop", "iterate", "for", "repeat"],
    correctAnswer: "for",
  },
  {
    id: 11,
    question: "How many times will this run?\nfor i in range(1, 6):",
    options: ["4", "5", "6", "Infinite"],
    correctAnswer: "5",
  },
  {
    id: 12,
    question: "What is the default start value in range()?",
    options: ["1", "0", "-1", "None"],
    correctAnswer: "0",
  },
  {
    id: 13,
    question: "Which statement is true about infinite loops?",
    options: [
      "They never stop",
      "They occur when loop has no exit",
      "They can crash the program",
      "All of these",
    ],
    correctAnswer: "All of these",
  },
  {
    id: 14,
    question: "What is the output?\nfor i in range(1, 6, 2): print(i)",
    options: ["1 2 3 4 5", "1 3 5", "2 4", "0 2 4"],
    correctAnswer: "1 3 5",
  },
  {
    id: 15,
    question: "What will happen?\nx = 0\nwhile x < 3:\n print(x)\n x += 1",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "Infinite"],
    correctAnswer: "0 1 2",
  },
  {
    id: 16,
    question: "Which of the following can be used inside loops?",
    options: ["if", "continue", "break", "All of these"],
    correctAnswer: "All of these",
  },
  {
    id: 17,
    question: "How to write a loop to print 1 to 5?",
    options: ["for i in range(1,6):", "for i in range(0,5):", "for i in 1..5", "while i <= 5"],
    correctAnswer: "for i in range(1,6):",
  },
  {
    id: 18,
    question: "Which loop is better when number of iterations is unknown?",
    options: ["for", "while", "do-while", "None"],
    correctAnswer: "while",
  },
  {
    id: 19,
    question: "What is the output?\nfor i in range(3):\n if i == 1:\n  continue\n print(i)",
    options: ["0 1 2", "1 2", "0 2", "0 1"],
    correctAnswer: "0 2",
  },
  {
    id: 20,
    question: "Which is not a loop control statement?",
    options: ["break", "skip", "continue", "pass"],
    correctAnswer: "skip",
  },
  {
    id: 21,
    question: "What happens if loop condition is always True?",
    options: ["Normal loop", "Syntax error", "Infinite loop", "Loop skips"],
    correctAnswer: "Infinite loop",
  },
  {
    id: 22,
    question: "Nested loop means?",
    options: [
      "Two or more loops inside one another",
      "Single loop only",
      "Loop in function",
      "Loop without condition",
    ],
    correctAnswer: "Two or more loops inside one another",
  },
  {
    id: 23,
    question: "What is the output?\nfor i in range(2):\n for j in range(2):\n  print(i+j)",
    options: ["0 1 2", "0 1 1 2", "0 1 1 2", "0 1 1 2"],
    correctAnswer: "0 1 1 2",
  },
  {
    id: 24,
    question: "Which of the following is true about loops?",
    options: ["Loops repeat code", "Loops cannot be nested", "Only while is used", "Loops must end in 3 steps"],
    correctAnswer: "Loops repeat code",
  },
  {
    id: 25,
    question: "Which is the correct syntax for while?",
    options: ["while(x<5){ }", "while x<5:", "while x < 5 then:", "while < 5:"],
    correctAnswer: "while x<5:",
  },
  {
    id: 26,
    question: "What is the step value in range(1,10,2)?",
    options: ["1", "2", "10", "0"],
    correctAnswer: "2",
  },
  {
    id: 27,
    question: "Which value of x ends this loop?\nwhile x < 10:",
    options: ["x >= 10", "x < 10", "x == 10", "x != 10"],
    correctAnswer: "x >= 10",
  },
  {
    id: 28,
    question: "What is the output?\nfor i in range(3):\n print('Hi')",
    options: ["Hi", "Hi Hi Hi", "0 1 2", "3 times"],
    correctAnswer: "Hi Hi Hi",
  },
  {
    id: 29,
    question: "Which loop is better for traversing a list?",
    options: ["for", "while", "do-while", "if"],
    correctAnswer: "for",
  },
  {
    id: 30,
    question: "Which is valid loop control structure?",
    options: ["if-else", "for-else", "for-if", "while-if"],
    correctAnswer: "for-else",
  },
];

export default loopsTest;
