const operatorsTest = [
  {
    id: 1,
    question: "What is the output of: 10 + 3 * 2?",
    options: ["26", "16", "20", "13"],
    correctAnswer: "16",
  },
  {
    id: 2,
    question: "Which operator is used for exponentiation in Python?",
    options: ["^", "**", "^^", "//"],
    correctAnswer: "**",
  },
  {
    id: 3,
    question: "What is the result of: 10 // 3?",
    options: ["3", "3.33", "3.0", "Error"],
    correctAnswer: "3",
  },
  {
    id: 4,
    question: "What does the '%' operator do?",
    options: ["Division", "Modulo", "Exponent", "Floor division"],
    correctAnswer: "Modulo",
  },
  {
    id: 5,
    question: "Which operator is used for logical AND in Python?",
    options: ["&&", "AND", "and", "&"],
    correctAnswer: "and",
  },
  {
    id: 6,
    question: "What is the output of: 5 == 5.0?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "True",
  },
  {
    id: 7,
    question: "Which operator checks if two values are not equal?",
    options: ["<>", "!=", "~=", "==!"],
    correctAnswer: "!=",
  },
  {
    id: 8,
    question: "What is the result of: True and False?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "False",
  },
  {
    id: 9,
    question: "What is the output of: 4 > 2 and 3 < 1?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "False",
  },
  {
    id: 10,
    question: "Which operator returns True only if both conditions are False?",
    options: ["and", "or", "not", "xor"],
    correctAnswer: "not",
  },
  {
    id: 11,
    question: "Which operator is used for logical OR?",
    options: ["||", "or", "|", "OR"],
    correctAnswer: "or",
  },
  {
    id: 12,
    question: "What is the output of: not True?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "False",
  },
  {
    id: 13,
    question: "What is 2 ** 3?",
    options: ["6", "8", "9", "4"],
    correctAnswer: "8",
  },
  {
    id: 14,
    question: "What is 15 % 4?",
    options: ["3", "4", "1", "0"],
    correctAnswer: "3",
  },
  {
    id: 15,
    question: "What is the output of: 7 > 5 and 6 < 9?",
    options: ["True", "False", "None", "Error"],
    correctAnswer: "True",
  },
  {
    id: 16,
    question: "What is the output of: 4 != 4?",
    options: ["True", "False", "None", "Error"],
    correctAnswer: "False",
  },
  {
    id: 17,
    question: "What is the result of: 7 <= 7?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "True",
  },
  {
    id: 18,
    question: "What is the output of: 2 + 3 * 4?",
    options: ["14", "20", "24", "18"],
    correctAnswer: "14",
  },
  {
    id: 19,
    question: "Which operator gives remainder?",
    options: ["//", "/", "**", "%"],
    correctAnswer: "%",
  },
  {
    id: 20,
    question: "Which is a relational operator?",
    options: ["+", "*", "<", "**"],
    correctAnswer: "<",
  },
  {
    id: 21,
    question: "What is the output of: not False?",
    options: ["False", "True", "None", "Error"],
    correctAnswer: "True",
  },
  {
    id: 22,
    question: "What does '==' do in Python?",
    options: ["Assign value", "Compare identity", "Compare values", "None"],
    correctAnswer: "Compare values",
  },
  {
    id: 23,
    question: "Which operator is used for floor division?",
    options: ["//", "/", "%", "**"],
    correctAnswer: "//",
  },
  {
    id: 24,
    question: "Which operator checks if a < b and a != b?",
    options: ["a < b", "a <= b", "a != b", "a < b and a != b"],
    correctAnswer: "a < b and a != b",
  },
  {
    id: 25,
    question: "What is the output of: 3 + 5 > 10 or 4 < 9?",
    options: ["True", "False", "None", "Error"],
    correctAnswer: "True",
  },
  {
    id: 26,
    question: "What is the precedence of arithmetic operators?",
    options: ["+ before *", "* before +", "- before **", "/ before *"],
    correctAnswer: "* before +",
  },
  {
    id: 27,
    question: "Which operator is used to negate a boolean value?",
    options: ["not", "!", "~", "None"],
    correctAnswer: "not",
  },
  {
    id: 28,
    question: "What will be the result of: 2 != 3 and 3 == 3?",
    options: ["True", "False", "Error", "None"],
    correctAnswer: "True",
  },
  {
    id: 29,
    question: "Which expression evaluates to False?",
    options: ["4 < 5", "2 == 2", "5 != 5", "3 <= 3"],
    correctAnswer: "5 != 5",
  },
  {
    id: 30,
    question: "What is the output of: 2 + 3 * 2 ** 2?",
    options: ["16", "10", "20", "14"],
    correctAnswer: "14",
  },
];

export default operatorsTest;
